package ModAuthFIT;


/**
* ModAuthFIT/AuthFIT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuthFIT.idl
* Wednesday, November 30, 2016 7:10:06 PM GMT
*/

public interface AuthFIT extends AuthFITOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AuthFIT
