package ModAuthFIT;

/**
* ModAuthFIT/AuthFITHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuthFIT.idl
* Wednesday, November 30, 2016 7:10:06 PM GMT
*/

public final class AuthFITHolder implements org.omg.CORBA.portable.Streamable
{
  public ModAuthFIT.AuthFIT value = null;

  public AuthFITHolder ()
  {
  }

  public AuthFITHolder (ModAuthFIT.AuthFIT initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModAuthFIT.AuthFITHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModAuthFIT.AuthFITHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModAuthFIT.AuthFITHelper.type ();
  }

}
