package ModAuthFIT;


/**
* ModAuthFIT/AuthFITOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuthFIT.idl
* Wednesday, November 30, 2016 7:10:06 PM GMT
*/

public interface AuthFITOperations 
{
  boolean addUser (String login, String password);
  boolean authUser (String login, String password);
  boolean changePassword (String login, String password, String new_password);
  boolean deleteUser (String login, String password);
  void shutdown ();
} // interface AuthFITOperations
